spring:
  application:
    name: UserService
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql


